### PR TITLE
Enforce forward slashes as path separators

### PR DESCRIPTION
**Pull request by belluzj**
https://github.com/LettError/designSpaceDocument/issues/22

### CODE REVIEW

**Comment by anthrotype** [comment]
lgtm

**Comment by belluzj** [comment]
If the [implementation in MutatorMath](https://github.com/LettError/MutatorMath/pull/95/files#diff-78056da8d4ea3433bb8d6d8e828be027R100) is validated, I should maybe also use it in this project's code, for [example here](https://github.com/LettError/designSpaceDocument/blob/master/Lib/designSpaceDocument/__init__.py#L1018)?

**Review by anthrotype — APPROVED** [review]

**Comment by belluzj** [comment]
I have added some code but I couldn't run the tests locally, because some test files are missing:

```
λ python Lib\designSpaceDocument\__init__.py
Traceback (most recent call last):
  File "Lib\designSpaceDocument\__init__.py", line 2179, in <module>
    __removeAxesFromDesignSpace(p)
  File "Lib\designSpaceDocument\__init__.py", line 1313, in __removeAxesFromDesignSpace
    f = open(path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'testCheck.designspace'
```

**Comment by anthrotype** [comment]
@LettError can we get this merged?

**Pull request merged**
